version: '3.8'

services:
  web:
    build: .
    image: ${DOCKER_USER}/novra-simple-social-media:latest
    container_name: laravel-web
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: social_media
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/var/www/sosmed
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: social_media
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql-data:

networks:
  laravel:

