name: Laravel Docker CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/novra-simple-social-media:latest
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted  # Ganti ke ubuntu-latest jika deploy di server publik

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop running containers
        run: docker compose down

      - name: Pull new image
        run: docker pull $IMAGE_NAME

      - name: Start updated containers
        run: docker compose up -d
